### ISSUE TITLE
New project popup doesn't properly show dropdown background colors

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#103]
As can be seen here: 

<img width="592" alt="image" src="https://github.com/user-attachments/assets/53553ad1-0cf6-4fa5-9eb0-93114d0ea1fd">

**Comment by popovaevgeniya** [comment]
Hi @gorkem-bwl 
What should the background colors be? I couldn't find an open dropdown in figma.

**Comment by gorkem-bwl** [comment]
You can check it from the style guide, [here](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=1-17952&t=MAgH9CRx7FrqzMXK-1).

Basically it's #F9FAFB - and this needs to be applied to the components as well, since the same issue holds on Vendors page too.
