### ISSUE TITLE
Vendor view design

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#11]
A vendor is a company attached to a project. Each project may have one or more vendors, which are defined on this page. The table includes a list of external entity that provides AI-related products, services, or components. The user can create and manage all vendors here.

<img width="1179" alt="Screenshot 2024-09-19 at 12 17 25 PM" src="https://github.com/user-attachments/assets/0424c558-d351-4584-aca3-8f2ab4e87c50">

User can add a new vendor by clicking on "Add new vendor". 

"Add new vendor" and "Edit new vendor" popups are the same. One adds a new vendor, and the other edits a current vendor.

Tasks: 

- [x] Show vendors list
- [x] Add a new vendor
- [x] Edit a vendor 
- [x] Remove a vendor

**Comment by gorkem-bwl** [comment]
The project selector has been moved to the sidebar.

<img width="1004" alt="Screenshot 2024-09-24 at 10 45 27 PM" src="https://github.com/user-attachments/assets/934f14f6-46e2-4358-acb2-3142a416df3f">

**Comment by MuhammadKhalilzadeh** [comment]
Okay 👍🏻
