### ISSUE TITLE
Drop down background decoration

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#137]
Please add background decoration (same color as the active line).

<img width="655" alt="SCR-20241022-mckt" src="https://github.com/user-attachments/assets/6fcae94e-fb08-436c-baee-bc01214f8a58">

**Comment by gorkem-bwl** [comment]
@surijatin when we are done with a task related to UI, could you either add a screenshot or a video depicting the final interface?

**Comment by surijatin** [comment]
@gorkem-bwl Adding the video here for reference.

https://github.com/user-attachments/assets/23902eb5-0fe2-4471-950e-9ea8e7432e6e

**Comment by gorkem-bwl** [comment]
Looks good, thank you.
