### ISSUE TITLE
Compliance Tracker: All tables, panes, popups, or anything that reads/writes the data from/to the backend

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#151]
Addressing the issue #147 
Please read the instructions on the Main issue carefully

**Comment by melpsh** [comment]
Hi @HarshP4585,

I’m working on status handling for the compliance tracker, but I couldn’t locate the correct endpoint. Could you let me know which endpoint I should use to post data in the control pane?
You can take a look at #147 if you have some questions.
Thanks so much!
