### ISSUE TITLE
Fix tabbed bar background

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#167]
In the following screenshot, the tabbed bar has a bg of #FFFFFF whereas the whole popup has the bg color of #FCFCFD (this one is correct).

<img width="854" alt="image" src="https://github.com/user-attachments/assets/1e24f5c3-0d2c-46eb-afaa-fb69ac87d916">

**Comment by melpsh** [comment]
Hi @gorkemcetin  Could you please elaborate on this issue? I don't understand what should I fix. Thank you

**Comment by gorkem-bwl** [comment]
Sure, let me explain. The tabbed bar is now mentioned with a red rectangle. Its bg color is #FFFFFF but should have been #FCFCFD.

<img width="854" alt="380537053-1e24f5c3-0d2c-46eb-afaa-fb69ac87d916" src="https://github.com/user-attachments/assets/86e64749-7047-4373-8b79-e23d2c4e9901">

**Comment by melpsh** [comment]
![image](https://github.com/user-attachments/assets/7fdd6221-93f3-4c7f-bc3a-4807afbaa430)
![image](https://github.com/user-attachments/assets/78d5c243-4f3f-400e-b68d-d3a835864d83)

Hi, Gorkem I fixed this to the color you mentioned I don't see the difference so if I was wrong please let me know.

**Comment by gorkem-bwl** [comment]
Yes, that is fixed. I know it's very hard to see the difference but it bugged me honestly :-D Thank you!

**Comment by melpsh** [comment]
> Yes, that is fixed. I know it's very hard to see the difference but it bugged me honestly :-D Thank you!

Of course
