### ISSUE TITLE
Create button group component

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#170]
A button group component is lacking in Components folder, so two button groups in the app have different stylings. 

[Here is the button group design on Figma](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=1-18057&t=OKpO8xfcTbnMvFHk-1) that should be implemented. 

Screenshot: 

<img width="581" alt="image" src="https://github.com/user-attachments/assets/5f19f495-640a-4f97-b3b9-397bc0ae56e4">

**Comment by sankettank66** [comment]
@gorkem-bwl I want work on this issue.

**Comment by gorkem-bwl** [comment]
Go ahead please. Make sure you check other components styling and how we use MUI.

**Comment by gorkem-bwl** [comment]
I'm checking back here @sankettank66 to see if you're done with this.

**Comment by gorkem-bwl** [comment]
@salmanja this is a good first issue for you to work on a component. This is a nonexistent component but we need it on the dashboard. You can see the design on Figma (it's in the link).
