### ISSUE TITLE
Inconsistencies in Vendors pages and data

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#171]
### Vendors view

**In the UI & Design:**

**The table loads the following values:**
`Name, Type, Assignee, Status, Risk, Review date`

![Screenshot (184)](https://github.com/user-attachments/assets/622120e9-7d55-4ad1-aee0-50b0ed86fc21)

**In the Mock data, we have the following in the backend with the values:**
`id, name, project_id, description, website, contact_person, review_result, review_status, reviewer_id, review_date, risk_status`

![Screenshot 2024-10-30 111401](https://github.com/user-attachments/assets/c6075a6b-2ba2-4ba4-9271-bc3df7e26511)

**And we have this is the frontend with following fields:**
`name, type, assignee, status, risk, reviewDate`

![Screenshot 2024-10-30 111718](https://github.com/user-attachments/assets/68ba588f-81c9-486b-a78e-ba0f6b39b20a)

**Now, this is the Schema in ERD diagram:**

![Screenshot 2024-10-30 111847](https://github.com/user-attachments/assets/43c27233-b0a0-42f8-ab09-95ed65f4d154)

**Comment by gorkem-bwl** [comment]
Here is the ERD diagram for vendors page: 

<img width="586" alt="image" src="https://github.com/user-attachments/assets/b9514718-1ee4-41d6-a41d-afe2bdbc4c98">

The mock data is updated here: https://github.com/bluewave-labs/verifywise/blob/master/Clients/src/presentation/mocks/vendors/vendors.data.ts
