### ISSUE TITLE
Inconsistencies in Vendors: Add new vendor: Vendor details

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#172]
**This is the UI & Figma design with following fields:**

- Vendor name
- Project the vendor is connected to
- What does the vendor provide?
- Website
- Vendor contact person
- Review result
- Review status
- Reviewer
- Risk status
- Review date

![Screenshot 2024-10-30 113015](https://github.com/user-attachments/assets/a41beacf-6e78-43fc-93c3-6196375228df)

Now, the mock data in frontend with the following fields:

- vendorName
- projectConnected
- servicesProvided
- website
- contactPerson
- reviewResult
- reviewStatus
- reviewer
- riskStatus
- reviewDate

![Screenshot 2024-10-30 113524](https://github.com/user-attachments/assets/3d107dd8-5f14-4b6e-ba67-eb2d7241dd7d)

And here's the schema in diagram, the two schemas we have:

![Screenshot 2024-10-30 113812](https://github.com/user-attachments/assets/242c1e59-5aa2-47ce-9d12-7e72e373ef7e)
![Screenshot 2024-10-30 113758](https://github.com/user-attachments/assets/d74c3360-df39-4ad0-bc7b-b94f580bbf8c)

**Comment by gorkem-bwl** [comment]
Added in #171
