### ISSUE TITLE
Inconsistencies in Vendors: Add new vendor: Risks

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#173]
**This is what we have in the UI & Figma design with following fields:**

```
1. Risk description
2. Impact description
3. Project name
4. Probability
5. Impact
6. Action plan
7. Action owner
8. Risk severity
9. Likelihood
10. Risk level
```

![Screenshot 2024-10-30 114101](https://github.com/user-attachments/assets/eeceedf6-2615-4190-b24e-cc377bdfeeaf)

**The mock data that we have:**

```
1. riskDescription
2. impactDescription
3. projectName
4. probability
5. impact
6. actionOwner
7. riskSeverity
8. likelihood
9. riskLevel
10. actionPlan
```

![Screenshot 2024-10-30 114807](https://github.com/user-attachments/assets/3475b62b-6d62-4624-ad60-9fb05c8b6623)

**The two schemas we have:**

![Screenshot 2024-10-30 113812](https://github.com/user-attachments/assets/081308ca-d1e0-48ea-99d7-286956a2ff4b)
![Screenshot 2024-10-30 113758](https://github.com/user-attachments/assets/7d8573e4-71c4-458c-8f7d-08b1165723a7)

**Comment by gorkem-bwl** [comment]
Added in #171
