### ISSUE TITLE
Modify vendor risks table under a Project

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#179]
We have a new, simplified vendor risks table under a project. The corresponding [Figma file is here](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=120-11078&t=7hxKa8OXaq7ZBgjn-1).

This is the screenshot:

<img width="753" alt="image" src="https://github.com/user-attachments/assets/714c5dbe-d8a7-4a03-ba9b-33abd33bbef1">

**Comment by gorkem-bwl** [comment]
Also fyi @HarshP4585

**Comment by harishankar1014** [comment]
Hi, I would also like to contribute to this project. Have worked a bit on this issue 
![Screenshot 2024-11-03 103108](https://github.com/user-attachments/assets/83d8acdd-0e80-4bda-af05-d818b39e7548)
Just one question: Is it okay to add a review date field to the VendorRisk mock data? Also any other suggestions on how I can contribute will be greatly appreciated.

**Comment by gorkem-bwl** [comment]
@harishankar1014 Most probably we don't have a review date in the mock data, but we can add. However we are re-reviewing the mock data with @MuhammadKhalilzadeh currently so it is better to hold this off for some time :) 

I can create two minor tasks. Let me know if that works for you today or tomorrow so I can open them and assign them to you.

- Add a client site sorting functionality for Vendor, risk level and review date.
- Add a colorful label for risk levels under "risk level" column so they are distinctive. [Have a look at the current colours here](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=0-1&t=gVh4EOflsYtrZaot-1). Note that we need a generic component for labels, so we can reuse them here.

**Comment by harishankar1014** [comment]
Hi @gorkem-bwl . I can try implementing the client side sorting functionality. Thanks.

**Comment by gorkem-bwl** [comment]
@harishankar1014 please go ahead and create a corresponding GitHub issue for this. Mention how you are going to fix it, and assign yourself (if you cannot assign, I can do as well).
