### ISSUE TITLE
Minor fixes in Compliance tracker

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#192]
There are a few wording fixes in Compliance Tracker dashboard:

<img width="1029" alt="SCR-20241102-rdse" src="https://github.com/user-attachments/assets/ef51e03c-7915-491a-9793-2c1cbdf1242e">

Also here as well:

<img width="812" alt="SCR-20241102-rjux" src="https://github.com/user-attachments/assets/9901ceaf-9c10-4c4c-8c28-0377e7cf737f">

**Comment by melpsh** [comment]
Hi Gorkem I was just looking at Figma design and the implementation and the design align perfectly:
What should I change in this issue?

![image](https://github.com/user-attachments/assets/90fd655a-9f38-4a66-86b7-e257f1dd0200)

**Comment by gorkem-bwl** [comment]
Can you please send a screenshot of your implementation for those areas? So I can directly point at them?

**Comment by melpsh** [comment]
Ohhhhh sorrry sorryyy I get it now I was looking at Figma. Iwill fix it right away. Thanks
