### ISSUE TITLE
 Inconsistencies in Compliance Tracker

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#194]
This is all what we have at hands for Compliance Tracker view.
Me and @melpsh tried to figure out which route should get http requests, but current data does not match

![Compliance Tracker Related Data](https://github.com/user-attachments/assets/30bd86e6-bdc2-4d82-acc5-cc8653c9a18b)

**Comment by melpsh** [comment]
This is the data returning:
![image](https://github.com/user-attachments/assets/6dd8b573-294b-4194-9b77-a31e160e5126)

**Comment by gorkem-bwl** [comment]
Thanks. Yes, today we'll go over the file "VeriftyWise High Risk Deployer AIA Control List", finalize it, and come up with some mock data.

**Comment by gorkem-bwl** [comment]
@HarshP4585 @MuhammadKhalilzadeh there shouldn't be any responses back for this. Also could you let Melina know the endpoints?

**Comment by MuhammadKhalilzadeh** [comment]
I talked this melina and this image is uploaded during our call. We're not sure which endpoint to use either 🤔 
The ui was not matching the mock data
