### ISSUE TITLE
Better representation of colors / completions in controls table

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#215]
We can have a few visual improvements on our requirements list that shows controls. 

1. The main logic behind displaying the icons is as follows: if all subcontrols are completed, a green checkmark icon is shown. If any subcontrol within a given control is incomplete, a yellow exclamation icon appears instead.
 
<img width="375" alt="image" src="https://github.com/user-attachments/assets/963f43e2-9b92-4cde-90aa-f57b6805b444">

2. The wording has slightly changed for the completion rates column.

<img width="207" alt="image" src="https://github.com/user-attachments/assets/80fbe946-7f91-4ecc-9c0d-415722887eb8">

3. The last column (showing the completion percentage) is now color coded. 

<img width="243" alt="image" src="https://github.com/user-attachments/assets/44701907-e552-4166-a94f-f223fd194a2a">

Here is the colour code table (0-20% has the same red color)

| Color Code | Range |
|------------|-------|
| #FF4500    | 0-10  |
| #FF4500    | 11-20 |
| #FFA500    | 21-30 |
| #FFD700    | 31-40 |
| #E9F14F    | 41-50 |
| #CDDD24    | 51-60 |
| #64E730    | 61-70 |
| #32CD32    | 71-80 |
| #228B22    | 81-90 |
| #008000    | 91-100|

**Comment by melpsh** [comment]
![image](https://github.com/user-attachments/assets/e6defbb7-324b-4b24-a970-0197b8d3598b)
