### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by popovaevgeniya** [bluewave-labs/verifywise#217]

**Comment by gorkem-bwl** [comment]
Here are the validation rules for Projects: 

Create new project: 
- Project title: 64 chars
- Goal: 256 chars

Add new vendor risk: 
- Risk description: 256 chars

Add new risk -> Risks
- Risk description: 256 chars
- Potential impact: 256 chars
- Review notes: 1024 chars

Add new risk -> Mitigation plan
- Mitigation plan: 1024 chars
- Implementation strategy: 1024 chars
- Recommendations: 1024 chars

**Comment by gorkem-bwl** [comment]
For the "required" part, I have added green dots to areas where that field is required as you click on Save. Example:
<img width="901" alt="image" src="https://github.com/user-attachments/assets/2062e721-86b0-4518-bc90-d27ab20c4f9d">
