### ISSUE TITLE
Refactors: Removing ripple effects in theme

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#23]
The ripple effect should be removed from: 

1. Dropdowns
2. Sidebar menus
3. Buttons
4. Icons

**Comment by gorkem-bwl** [comment]
This is what should go to the theme file:

`import { createTheme } from '@mui/material/styles';

const theme = createTheme({
  components: {
    MuiButtonBase: {
      defaultProps: {
        disableRipple: true, // Disable ripple globally for all components using ButtonBase
      },
    },
    MuiIconButton: {
      defaultProps: {
        disableRipple: true, // Disable ripple for IconButtons
      },
    },
    MuiFab: {
      defaultProps: {
        disableRipple: true, // Disable ripple for Floating Action Buttons
      },
    },
    MuiCheckbox: {
      defaultProps: {
        disableRipple: true, // Disable ripple for Checkboxes
      },
    },
    MuiSwitch: {
      defaultProps:
`

**Comment by MuhammadKhalilzadeh** [comment]
- [ ] Sidebar
- [ ] Vendor view
- [ ] Dashboard
- [ ] Assessment tracker
- [ ] Compliance Tracker
