### ISSUE TITLE
Compliance tracking metadata

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#244]
General metadata applies to each and every control in the compliance tracker. It has the following metadata:

1. Status: Waiting, in progress or done
2. Approver: One of the users in the system
3. Risk review: Acceptable risk, residual risk or unacceptable risk
4. Owner: One of the users in the system
5. Reviewer: One of the users in the system 
6. Due date: Due date of the control

<img width="673" alt="image" src="https://github.com/user-attachments/assets/18f5ac47-6d4e-40d1-bfc5-75c285257bfa">

FYI @MuhammadKhalilzadeh @HarshP4585 as well.

**Comment by melpsh** [comment]
To complete this task, I need access to the list of users in the system.  I need a list of users with their IDs and names (or any relevant identifiers). @HarshP4585 @MuhammadKhalilzadeh , Please let me know how I can get this information. Thank you

**Comment by melpsh** [comment]
Hi, @HarshP4585  @MuhammadKhalilzadeh I am still waiting for this information. Please kindly provide information.
Thank you

**Comment by MuhammadKhalilzadeh** [comment]
@melpsh 
Is this one resolved for you finally?

Btw, I'm un-assigning it for now from you.
