### ISSUE TITLE
Font size fixes in delete account modal popup

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#257]
The modal popup contents should honor our standard font styles.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/0383d68f-d056-471c-a229-0af689e4eee6">

**Comment by melpsh** [comment]
Updated as requested,
![1](https://github.com/user-attachments/assets/09819f07-6e28-4e02-a334-df6105955bf2)

**Comment by gorkem-bwl** [comment]
Looks good, thanks.
