### ISSUE TITLE
Invisible buttons in compliance tracker

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#260]
A compliance tracker modal, when popped up, doesn't have a scrollbar. Hence the buttons are halfway invisible. We need to add an automatically visibel scrollbar there for smaller screens.

<img width="696" alt="image" src="https://github.com/user-attachments/assets/02f7d58d-9bf9-44bb-9dc0-03ebdd8e0b88">

**Comment by melpsh** [comment]
UI updated as requested:

![image](https://github.com/user-attachments/assets/1297dbd1-5a9e-40c5-954a-d2fd84440ad3)

**Comment by gorkem-bwl** [comment]
Looks good, thanks.
