### ISSUE TITLE
Delete Transacrions

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#287]
When an entity is deleted from the database, all other entities on lower levels of the diagram that depend on it must be deleted as well.
This is a mechanism that somehow already exists in the **PostgreSQL**, but you need to propagate the error to the UI in a friendly manner.

_Please pay close attention to the hierarchy of the diagram._

![Untitled diagram-2024-11-07-192334 1](https://github.com/user-attachments/assets/74a5861f-7140-4614-b0b8-14255b6f84cd)

**Comment by HarshP4585** [comment]
This mechanism is already working in the existing code but it was not being used as we were using MOCK_DATA for all the API calls, I raised the PR #304 for using the value set in the env file for the MOCK_DATA flag to use the DB for the API calls.
