### ISSUE TITLE
Compliance tracker

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#311]
Hi @melpsh 

Similar to what we've done in earlier tasks, please make sure no fields (in case they are required) will remain empty or get values that are not match with their type of inputs.

Thank you so much in advance. 🙏🏼

**Comment by melpsh** [comment]
@gorkem-bwl which fields are required in the compliance tracker?

**Comment by gorkem-bwl** [comment]
@MuhammadKhalilzadeh fyi, we arranged this with @melpsh
