### ISSUE TITLE
Double Checking the Mock data relations (FKs)

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#314]
Dear @HarshP4585 and @gorkem-bwl 

Please go through the mock data in each file according to the order inside the ERD diagram from top to bottom and make sure the relationship between the data is correct and foreign keys are also set correctly.

Thank you so much in advance. 🙏🏼

**Comment by gorkem-bwl** [comment]
Sure, we can hop on a call about this. Just sent the invite.

**Comment by MuhammadKhalilzadeh** [comment]
Great
