### ISSUE TITLE
Providing descriptions and the Story in the Figma design files

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#46]
In order to have a clear understanding of the way and direction of the data flow and the navigation between pages, we need to understand the story behind every page, what it does, what goal the whole dataflow in our app serves, and etc.

- [x] Please provide description for each page
- [x] Please mark the navigation between pages
- [x] Please write the story of the app

**Comment by Mertcanboyar** [comment]
@MuhammadKhalilzadeh Hey Mo, I just finished these tasks. We can jump on a call call this week if you need any clarifications.
