### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#47]
The profile page of the VerifyWise application has the following tabs:

- Profile: The user can set first name, last name and photo. Email address is immutable. Here the user can also remove the username from the database.
- Password: The user can give the current password and then set a new password. The new password must contain at least 8 characters and must have at least one uppercase letter, one number and one symbol.
- Team: This is only visible to the admin - the first logged-in user. The admin can invite a new user or an admin, change the role or remove other users/admins. The organization name can also be changed here. Initially, the organization name can be a random string, like "Stark Industries", and then can be modified by the admin. There are 3 different user types: Admin, Editor and Reviewer.

> [!TIP]
> The uptime-manager repository (https://github.com/bluewave-labs/bluewave-uptime) has all the required code, and it can be reused for this purpose. There might be slight differences between the Figma design. **The code we'll use from the Uptime Manager application will supersede the Figma design.**

**Profile tab** 

When the user clicks on the "Delete account" option, the account should completely be deleted from the database. An admin can remove anyone, as long as there is 1 admin left.

<img width="708" alt="Screenshot 2024-10-08 at 4 23 19 PM" src="https://github.com/user-attachments/assets/2cfaa139-f3ac-4946-b75a-6521dad69f52">

**Password tab** 

<img width="670" alt="Screenshot 2024-10-08 at 4 24 54 PM" src="https://github.com/user-attachments/assets/a0706b69-3be8-4a8a-a996-2c86eda0a662">

**Team tab**

<img width="641" alt="Screenshot 2024-10-08 at 4 29 18 PM" src="https://github.com/user-attachments/assets/19af2b88-395f-4754-83a2-652a5c422adf">

Tasks: 

Implement profile tab

- [x] General layout
- [x] 3 Text field for names
- [x] Note that 1 there is one immutable text field for password
- [x] Update link by clicking on the picture functionality
- [x] "Delete" button
- [x] "Update" button
- [x] "Save" button
- [x] "Delete account" button

 Implement password tab

- [x] General layout
- [x] 3 Text field for password and confirmation
- [x] Text information what is required at the alert box text location (that is currently showing on Figma)
- [x] Alert text box when requirements are not met
- [x] "Save" button

Implement team tab

- [x] General layout
- [x] Organization name edit widget and save button
- [x] Tab functionality for displaying administrators, reviewers or editors
- [x] "Invite team member" button
- [x] Member's list table
- [x] In the role section a dropdown menu for setting the member's role
- [x] Delete button for each member

**Comment by gorkem-bwl** [comment]
This is updated. FYI @MuhammadKhalilzadeh

**Comment by gorkem-bwl** [comment]
@melpsh when you have some time, can you please add screenshots to this issue?

**Comment by gorkem-bwl** [comment]
Ah nevermind - saw in your commit :)
