### ISSUE TITLE
Implementation of Models

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#49]
For the following models, these files are needed to be implemented:

- **Controllers, Endpoint-tests, Models, Routes, Utils**

- [x]  Vendor
- [x]  Risk
- [x]  Compliance_Tracker
- [x]  Assessment_Tracker
- [x]  VendorRisk
- [x]  Compliance_List
- [x]  Section
- [x]  Requirement
- [x]  Question
- [x]  Subrequirement
- [x] #111
- [x]  Overview
- [x] #112
- [x]  Auditor_Feedback

**Comment by MuhammadKhalilzadeh** [comment]
@HarshP4585 
**Question_Evidence** and **Subrequirement_Evidence** added to the schema on Figma, recently I guess.
So I'm pushing the Due date here so you can complete these two as well.

**Comment by HarshP4585** [comment]
> @HarshP4585 
> **Question_Evidence** and **Subrequirement_Evidence** added to the schema on Figma, recently I guess.
> So I'm pushing the Due date here so you can complete these two as well.

Sure. Thanks @MuhammadKhalilzadeh

**Comment by gorkem-bwl** [comment]
@MuhammadKhalilzadeh can we have a call about Question_Evidence and Subrequirement_Evidence today, for 15 mins or so, to make sure we are on the same page?

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
Of course 👍🏻
