### ISSUE TITLE
Status Codes and Redirecting Page

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#57]
Handle errors by redirecting or notifying the user.

For example, for status codes like 401 (Unauthorized), 403 (Forbidden), etc., instead of logging to the console, provide a better user experience by redirecting the user to the login page or showing an appropriate error message.

- [ ] UI implementation of the page

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
Do we have any designs for this purpose?

**Comment by gorkem-bwl** [comment]
For this purpose, let's go without a design for now, and only spit out the relevant message on the top side of the screen, or as a toast/snackbar. Does that look ok to you?

**Comment by MuhammadKhalilzadeh** [comment]
Of course 👍🏻
