### ISSUE TITLE
Authentication: Capturing input values and validations

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#64]
In each of the following pages:

- [x] Admin account creation
- [x] Create an account
- [x] Login
- [x] Forgot password
- [x] Set new password
- [x] etc.

If there's any input fields, you need to:

1. Get the input values
2. Implement input validation check

_Please make separate pull requests for each page as you move forward._

**Comment by sankettank66** [comment]
Hello @MuhammadKhalilzadeh ,

I want to work on this issue, and I have already addressed it as per the discussion in #77 .

**Comment by MuhammadKhalilzadeh** [comment]
@sankettank66 Yes. Feel free to work on the task. 👍🏻🍻

**Comment by sankettank66** [comment]
@MuhammadKhalilzadeh, please assign me this issue. I started working on it.

**Comment by MuhammadKhalilzadeh** [comment]
Done ✅
