### ISSUE TITLE
Dashboard and Projects view

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#7]
Create the dashboard and projects view. The dashboard is the main screen when the user first logs in. It includes a list of projects, together with a general overview of compliance status. The user can also create a new project in this page by clicking on "New project".

<img width="1440" alt="Dashboard" src="https://github.com/user-attachments/assets/71c1ef43-5900-4544-8d4f-45bdac308e30">

When the user clicks on a project, a detailed project page appears. Here there are 4 tabs (Overview, Project risks, Vendor risks and Settings). 

- Overview: Shows an overview of current project 
- Project risks: Shows project risks
- Vendor risks: Shows vendor risks associated with the project
- Settings: Shows different settings for the project.

![Project risks view](https://github.com/user-attachments/assets/1f2849eb-7236-43ff-92f1-2cbae7ed488d)

The risks  table is too big that it may not fit in the dashboard, which is OK. If the user wants to horizontally move in the table, the “Vendor name” should be pinned. For more information about pinning a column in MUI, [see this document](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=120-10993&t=OF0EMCojdmLt9vZ4-1)

When the user wants to add a vendor risk, "Add new risk" button is used. If the user clicks on this button, the following popup appears: 

![modify risk (risks section)](https://github.com/user-attachments/assets/92f2d0f0-dc72-44fc-8194-237d5b1f25f2)

Tasks for the Dashboard:

- [x] Create the main dashboard and show projects
- [x] Show compliance tracker
- [x] Create the "New project" popup
- [x] Create an empty state

Tasks for the Project View: 

- [x] Create Overview tab
- [x] Create Project risks tab
- [x] Create Vendor risks tab
- [x] Add vendor risks popup
- [x] Create Settings tab

**Comment by gorkem-bwl** [comment]
@popovaevgeniya I have added an empty state. In the case of no projects available to view on the dashboard, this empty state will be shown. 

[Here is the link to the Figma file](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=488-5509&t=OF0EMCojdmLt9vZ4-1).

Here is the screenshot:

<img width="1440" alt="Dashboard - empty state" src="https://github.com/user-attachments/assets/ed2baea7-bd38-4494-b113-9bbc9b58fe20">

**Comment by gorkem-bwl** [comment]
@popovaevgeniya added "Last updated" box here:

![Projects view](https://github.com/user-attachments/assets/4bfc8dfc-a995-4c24-a974-3899423bc83d)

[Link to Figma design](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=120-10993&t=OF0EMCojdmLt9vZ4-1)

**Comment by gorkem-bwl** [comment]
@popovaevgeniya "Add a new risk" popup has a few changes. Please refer to Figma design [here](https://www.figma.com/design/o4xu4PeC5bo1Ii4dyom6vQ/VerifyWise?node-id=573-4191&t=wof4JJCB8sMcIJQK-1).

**Comment by gorkem-bwl** [comment]
@popovaevgeniya previously, the project selector was on the top right hand side. It is now moved to the sidebar, so you don't have to implement a popup there (or remove if you have already done).

<img width="1004" alt="Screenshot 2024-09-25 at 7 22 55 PM" src="https://github.com/user-attachments/assets/ef503890-1557-4949-bafb-e8acf1976230">

**Comment by MuhammadKhalilzadeh** [comment]
@popovaevgeniya Please do not forget to **Check** ✅ the tasks you've completed here
