### ISSUE TITLE
Getting input values: Authentication pages

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#77]
Here's a code sample example:

```
import React, { useState } from 'react';
import { TextField, Select, MenuItem, Button } from '@mui/material';

const MyForm: React.FC = () => {
    const [textField1, setTextField1] = useState('');
    const [textField2, setTextField2] = useState('');
    const [selectValue, setSelectValue] = useState('');

    const handleSend = () => {
        console.log('TextField1:', textField1);
        console.log('TextField2:', textField2);
        console.log('Select:', selectValue);
    };

    return (
        <div>
            <TextField
                label="TextField 1"
                value={textField1}
                onChange={(e) => setTextField1(e.target.value)}
            />
            <TextField
                label="TextField 2"
                value={textField2}
                onChange={(e) => setTextField2(e.target.value)}
            />
            <Select
                value={selectValue}
                onChange={(e) => setSelectValue(e.target.value as string)}
            >
                <MenuItem value=""><em>None</em></MenuItem>
                <MenuItem value="Option1">Option 1</MenuItem>
                <MenuItem value="Option2">Option 2</MenuItem>
            </Select>
            <Button onClick={handleSend}>Send</Button>
        </div>
    );
};

export default MyForm;

```

**Comment by sankettank66** [comment]
Hi @MuhammadKhalilzadeh ,

I would like to contribute to this task. Could you please assign it to me? I also have one question.

Is the task simply to check validation, retrieve values from the input, and log them to the console upon submission?

**Comment by MuhammadKhalilzadeh** [comment]
Hello @sankettank66 
Nice to meet you!
Of course.
Assigned to you! 😊🍻

**Comment by MuhammadKhalilzadeh** [comment]
@sankettank66 
That's exactly what's required in this task.

**Comment by sankettank66** [comment]
Hello @MuhammadKhalilzadeh,

As per requirements, I have implemented input value capturing in the following authentication views:

- `/forgot-password`
- `/login`
- `/admin-reg`
- `/user-reg`
- `/set-new-password`

Additionally, I have implemented proper validation for the code with robust error handling. Upon successful submission, the input values will be logged in the console.

I have a concern regarding the console logging, as it seems that the statement was removed by coderabbitai. 
If there are no changes in PR #94 , could you please add the tags "hacktoberfest" and "hacktoberfestaccepted" if possible?

Please let me know if any changes are needed. Thank you!

**Comment by gorkem-bwl** [comment]
> If there are no changes in PR #94 , could you please add the tags "hacktoberfest" and "hacktoberfestaccepted" if possible?

We have it in the repo already, so no need to add it to the PR.

**Comment by MuhammadKhalilzadeh** [comment]
@sankettank66 Please forget about the validation for now and simply capture values and log them.

**Comment by sankettank66** [comment]
> @sankettank66 Please forget about the validation for now and simply capture values and log them.

Hello @MuhammadKhalilzadeh ,

As per your request, I have removed the validation in the code. Now, it will simply log the values to the console. You can check PR number #94 . Let me know if there are any changes needed.

**Comment by sankettank66** [comment]
@MuhammadKhalilzadeh, Thank you for merging my PR!🙏🏻
You can close this issue now. I am also working on #64.
